apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tracing-demo
  labels:
    app: tracing-demo
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: tracing-demo
  namespaceSelector:
    any: true
  endpoints:
    - port: web
      path: /actuator/prometheus
      interval: 30s
