apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
  - namespace.yaml
  - serviceAccount.yaml
  - volume.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
